version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: [gpu]


networks:
  app-network:
    driver: bridge